# -*- coding: utf-8 -*-
"""testcar-nomiddleline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11glaGjWmjs-A4DPhsCgp6xWooACcJohy
"""

from picamera.array import PiYUVArray, PiRGBArray
from picamera import PiCamera

from scipy.signal import find_peaks, butter, filtfilt

import time
import matplotlib.pyplot as plt
import skimage as ski
import numpy as np

# Camera resolution
res = (640, 480)

CAMERA_CENTER = res[0] // 2
       
from pwm import PWM

"""## Setup servo and motor PWM signal to control the steering angle and the speed.

The values specified period and duty cycle ar in nanoseconds.

Servo and motor controlled follow the following protocol:
  1. Control signal is read 50 times per second by each device (servo and speed controller). Thus period is 20 ms => 20000000 ns
  2. To send the minimum value (full left for servo and break for motor) the duty cycle should be 1 ms => 1000000 ns
  3. Maximum value corresponds to a duty cycle of 2 ms => 2000000 ns
  
However, these devices are not perfect and you can set a duty cycle outside this range and still get a response. I would recoment to play with it and find are the limits in your case. Pay attention that servo is limited by the mechanical construction how much it can turn the wheels. Do not set these limits to a value which servo cannot execute as it will try to do that and eventually burn.
"""

# Enable servo
SERVO_MIDDLE = 1500000

servo = PWM(1)
servo.period = 20000000
servo.duty_cycle = SERVO_MIDDLE
servo.enable = True

# Enable servo
MOTOR_BRAKE = 1000000

motor = PWM(0)
motor.period = 20000000
motor.duty_cycle = MOTOR_BRAKE
motor.enable = True

motor.duty_cycle = MOTOR_BRAKE

"""## The self driving code

Quick explanation on how this algorithm works:
  1. Initialize the camera, use a frame rate of 10 to 20 fps
  2. Get the coefficients of the butterworth filter of order 3 and cut-off frequency of 0.1 (change cut of frequency if the peak functions is not working)
  3. For each frame captured from the camera:
    1. Get the blak and white part of the image
    2. Select line 195 to use for lane detection (this number depends on your camera angle)
    3. Filter the line and find the peaks that are greater than 160. White parts of the image have higher values than the black. The threshold of 160 depends on the ambient light, lower if the room is darker
    4. Find the peaks left and right of the camera center, these peaks should corresponds to the white lines delimiting the track,
    5. Compute the center point between these lines. This is where we want our car
    6. Compute the error by substracting the center point from camera middle and multiply by 5000. 5000 is our P gain.
    7. Adjust the duty cycle of the servo such that the
"""

# Run a track detection algorithm on a single horizontal line.
# Uses YUV420 image format as the Y component corresponds to image intensity (gray image)
# and thus there is no need to convert from RGB to BW

## Run a track detection algorithm on a single horizontal line.
# Uses YUV420 image format as the Y component corresponds to image intensity (gray image)
# and thus there is no need to convert from RGB to BW

history=[]

camera = PiCamera()
        
# Check the link below for the combinations between mode and resolution
# https://picamera.readthedocs.io/en/release-1.13/fov.html#sensor-modes
camera.sensor_mode = 7
camera.resolution = res
camera.framerate = 10

# Initialize the buffer and start capturing
rawCapture = PiYUVArray(camera, size=res)
stream = camera.capture_continuous(rawCapture, format="yuv", use_video_port=True)

# Measure the time needed to process 300 images to estimate the FPS
t = time.time()

# To filter the noise in the image we use a 3rd order Butterworth filter

# Wn = 0.02, the cut-off frequency, acceptable values are from 0 to 1
b, a = butter(3, 0.1)

line_pos    = CAMERA_CENTER
first_frame = True

#######################
# Definition of p, i, d
#######################

# # 1. pass with d, p
# Kp,Ki,Kd = 10000,0,2500
# speed = 180000
# midspeed = 180000
# slowspeed = 140000

# # 2. pass with d, p
# Kp,Ki,Kd = 11500,0,2500
# speed = 200000
# midspeed = 200000
# slowspeed = 140000


# 3. pass with d, p
# Kp,Ki,Kd = 11000,0,2500
# speed = 190000
# midspeed = 190000
# slowspeed = 140000

# 4 pass with d, p ,i
Kp,Ki,Kd = 11500,10,2500
speed=220000
midspeed = 230000
slowspeed = 170000

# test with d, p
# Kp,Ki,Kd = 13000,0,2700
# speed=220000
# midspeed = 230000
# slowspeed = 170000

# start car

motor.duty_cycle = MOTOR_BRAKE + speed

TIMEPERIOD = 60
# TIMEPERIOD = 15
# PID config




# Kp,Ki,Kd = 12000,10,1000
# Kp,Ki,Kd = 9000,10,1000
# Kp,Ki,Kd = 11000,10,500
# current error, previous error, previous error of err_prev
err,err_prev,err_last,integral=0,0,0,0
errlist=[]

track=["o"]
increment = 0

# count = 0  # count of images
for f in stream:
    if first_frame:
        first_frame = False
        # Reset the buffer for the next image
        rawCapture.truncate(0)
        continue
    
    if (time.time() - t) > TIMEPERIOD:
        break
    # Get the intensity component of the image (a trick to get black and white images)
    I = f.array[:, :, 0]
    
    # Reset the buffer for the next image
    rawCapture.truncate(0)
    
    # Select a horizontal line in the middle of the image
#     L = I[300, :]
    L = I[250, :]
#     print("L:",L)

    # Smooth the transitions so we can detect the peaks 
    Lf = filtfilt(b, a, L)
    history.append(Lf)
#     print("LF:",Lf)

    # Find peaks which are higher than 0.5
    p = find_peaks(Lf, height=160)
    
    peaks = p[0]
    
    line_left   = None
    line_right  = None
    peaks_left  = peaks[peaks < CAMERA_CENTER]
    peaks_right = peaks[peaks > CAMERA_CENTER]
    
    if peaks_left.size:
        line_left = peaks_left.max()

    if peaks_right.size:
        line_right = peaks_right.min()
        
    if line_left and line_right:
        line_pos    = (line_left + line_right ) // 2
        track_width = line_right - line_left
        speed=midspeed
#         Kp=
        track.append("mid")
        
    elif line_left and not line_right:
        line_pos    = line_left + int(track_width / 2)
        speed=slowspeed
        track.append("turnRight")
        
    elif not line_left and line_right:
        line_pos    = line_right - int(track_width / 2)
        speed=slowspeed
        track.append("turnLeft")
    else:
        speed=slowspeed
        print("no line")
        
    
#     pid
    err = CAMERA_CENTER - line_pos
    if increment<=200000:
        integral += err
#     increment  = Kp*err
    diff = err-err_prev
#     increment = Kp*err + Kd* (err - err_prev)
#     increment = Kp*err + Ki*integral
    increment = Kp*err + Ki*integral + Kd* (err - err_prev)
    

    err_prev = err
    errlist.append(err)
    
  
    DUTY_CYCLE = SERVO_MIDDLE + increment
    if DUTY_CYCLE > 2000000:
        DUTY_CYCLE = 2000000
    if DUTY_CYCLE < 1000000:
        DUTY_CYCLE = 1000000
        
#     print("line_pos:",line_pos,"CAMERA", CAMERA_CENTER, "err", err,"difference",diff,"increment",increment)
#     print("now:",track[-1])
    
    ################################
    # threshold for takinng images #
#     ################################
#     if np.abs(err) > 40:
#         plt.imsave('%d.png'%count, I)
    ################################
    # threshold for takinng images #
    ################################

    
    
#     if abs(err)<11:
#         speed = speed+500
#     elif abs(err)>60:
#         speed = 160000
#     else:
#         speed = 180000
    
    motor.duty_cycle = MOTOR_BRAKE + speed
    
    servo.duty_cycle =  DUTY_CYCLE
#     print("speed:",speed)
#     print("-"*20)
    
#     count += 1
    
        
#Initialize lines position
#Check which lines are closer them in the next frame

        
        #print(line_pos)
        
motor.duty_cycle = MOTOR_BRAKE  

# with open('error_record.txt', 'w') as f:
#     f.write(np.array2string(errlist))
    
# Release resources
stream.close()
rawCapture.close()
camera.close()
motor.duty_cycle = MOTOR_BRAKE

plt.imshow(I)
print(peaks)

peaks = p[0]

line_left   = None
line_right  = None
peaks_left  = peaks[peaks < CAMERA_CENTER]
peaks_right = peaks[peaks > CAMERA_CENTER]

if peaks_left.size:
    line_left = peaks_left.max()
    
if peaks_right.size:
    line_right = peaks_right.min()
    
p

L = I[200, :]
b, a = butter(3, 0.1)
Lf = filtfilt(b, a, L)

plt.plot(L)
plt.plot(Lf)

plt.imshow(np.vstack(history))
